//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtDc_Billing.Entity_FR
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarcodeAndPath
    {
        public long BarcodeAndPathId { get; set; }
        public string ConsignmentNo { get; set; }
        public string FilePath { get; set; }
    }
}
