
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DtDc_Billing.Entity_FR
{

using System;
    using System.Collections.Generic;
    
public partial class GECSector
{

    public long GECSectorId { get; set; }

    public string SectorName { get; set; }

    public string Pf_code { get; set; }

    public string Pincode { get; set; }

    public Nullable<int> Priority { get; set; }

    public string City { get; set; }

}

}
