
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DtDc_Billing.Entity_FR
{

using System;
    
public partial class MonthlyDataAnalysis_Result1
{

    public string PFCode { get; set; }

    public Nullable<int> InvoiceCount { get; set; }

    public Nullable<decimal> TotalInvoiceAmount { get; set; }

    public Nullable<decimal> PaidAmount { get; set; }

    public Nullable<decimal> UnpaidAmount { get; set; }

    public string LastMonth { get; set; }

    public Nullable<decimal> CashAmount { get; set; }

    public string FranchiseName { get; set; }

    public string OwnerName { get; set; }

    public string Email { get; set; }

}

}
