
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DtDc_Billing.Entity_FR
{

using System;
    using System.Collections.Generic;
    
public partial class NewPaymentdetail
{

    public int Payment_Id { get; set; }

    public string Payment_Mode { get; set; }

    public Nullable<double> Amount { get; set; }

    public string InvoiceNo { get; set; }

    public Nullable<double> Tds_Amount { get; set; }

    public Nullable<double> Total_Amount { get; set; }

    public string Pfcode { get; set; }

    public Nullable<System.DateTime> Payment_Date { get; set; }

    public string Bank_Name { get; set; }

    public string Branch_Name { get; set; }

    public string Transaction_Id { get; set; }

    public string CheckNo { get; set; }

    public string CreditNoteNo { get; set; }

    public Nullable<double> Balance { get; set; }

    public Nullable<System.DateTime> Created_Date { get; set; }

}

}
