
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DtDc_Billing.Entity_FR
{

using System;
    using System.Collections.Generic;
    
public partial class Package
{

    public long Pid { get; set; }

    public Nullable<double> Amount { get; set; }

    public string Despription { get; set; }

    public Nullable<int> Subcriptionforindays { get; set; }

    public Nullable<bool> isPaid { get; set; }

}

}
