
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DtDc_Billing.Entity_FR
{

using System;
    using System.Collections.Generic;
    
public partial class PartyPaymentDetail
{

    public long PartyPaymentDetailId { get; set; }

    public string TransactionId { get; set; }

    public string CustomerId { get; set; }

    public Nullable<double> CreditAmount { get; set; }

    public Nullable<double> BalanceAmount { get; set; }

    public Nullable<System.DateTime> PaymentDate { get; set; }

    public string Status { get; set; }

    public string InvoicePaid { get; set; }

    public Nullable<int> InvoicePaidCount { get; set; }

    public Nullable<double> PaidAmount { get; set; }

}

}
